name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello:
    strategy:
      matrix:
        include:
          - runner: 'windows-2019'
          - runner: 'windows-2022'
    runs-on: ${{ matrix.runner }}
    steps:
      # - uses: actions/checkout@v4
      - run: systeminfo
      - run: get-localuser
      - run: whoami
      - run: tree C:\ /A
