name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello:
    strategy:
      matrix:
        include:
          - runner: 'windows-2019'
          - runner: 'windows-2022'
    runs-on: ${{ matrix.runner }}
    steps:
      - run: env
      # - uses: actions/checkout@v4
      - run: systeminfo > systeminfo.txt
      - run: get-localuser > localuser.txt
      - run: whoami > whoami.txt
      - run: Get-Location > whereami.txt
      # - run: tree C:\ /A > tree.txt
      - run: echo ${{ matrix.runner }}
